### ISSUE TITLE
Replicating the experiments

### ISSUE THREAD

**Issue by larifaxo** [ServiceNow/regions-of-reliability#1]
Hi, and thank you for your interesting paper and for publishing the code! However, I am not sure how to replicate your experiments. The csv file you provide contains 1000 rows per experiment (i.e. per combination of experiment name, metric name, dimensions, number of samples). If I run `ror/scripts/ror.py` (or `run_experiments` of `ror.experiments.h0_vs_h1.py`) with `trial_start=0`, `trial_end=1000` and e.g. `trial=0`, 1000 results like this are produced.

What is the purpose of `trial`, then? My first assumption was that one would need to repeat these experiments 30 times with different values for `trial`, and that this procedure corresponds to the $n=30$ you define in the paper as the ~forecast~ ground-truth sample size. Also the constant `NUM_DRAWS = 30` in `ror.experiments.h0_vs_h1.py` is not used in the experiment code (only for calibration), so maybe `trial` is supposed to go from 0 to `NUM_DRAWS`?

I wanted to verify by replicating the experiment for one example, however this did not work because trial is used to index e.g. `RNG_SEED_GT` in `ror.experiments.h0_vs_h1.py` which only has 10 entries and not 30. Also I noted, that the distribution of values I got for running the experiments only once fits to the results you provide in the csv file, so averaging this over 30 trials cannot be the solution.

Could you clarify this? Thank you!

**Comment by marcotet** [comment]
Firstly, thanks for your interest in reproducing our results.

As for `trial`, it is a relic of early code, before `trial_start` and `trial_end` were added. The idea was to run multiple independant experiments at the same time, before merging their results at the end. It stopped having any purpose when we saw that 1000 trials per experiment was already quite computationally intensive, and `trial_start` and `trial_end` was a better way to split an experiments into multiple independant processes.

On the note of reproducing our results, you may not be able to get exactly the same results, since we implemented the use of `np.random.SeedSequence` after having already started the experiments. I don't recall if we restarted all experiments, or only those who hadn't been completed after doing so, so the fastest to run experiments may show variations due to the random number generation.

**Comment by larifaxo** [comment]
Thanks for the quick reply! Does this mean that `NUM_DRAWS` is only applied to calibrate the experiments, but is not actually used to run the experiments? Because from reading your paper I would have expected that the evaluation would have to be repeated and averaged over 30 observed samples.

**Comment by marcotet** [comment]
`NUM_DRAWS` is indeed not used in running the experiments. It is only used in doing the calibration, and in the statistical analysis.
You are correct that in our paper we study the statistics of an experiment where the evaluation is repeated 30 (`NUM_DRAWS`) times. Given a much higher computational budget, we could have launched 1000 experiments with 30 evaluations each. Instead, we launched 1000 experiments of a single evaluation, and used these to approximate the distribution of the 30 evaluation experiment (using the law of great numbers and Gaussian distributions). This not only save compute time, but it also smooth out some of the numerical noise from the sampling process.
